[TRITON] Create script to benchmark attention kernels with shapes of LLM models (#2111)
* Refactor `bench_mha.py` main function to enable calls from other script

* Create script to benchmark attention kernels with shapes of LLM models

* Enable PE forward kernel with `(DQK=128+64, DV=128)` on `gfx950`

* Reducing `num_stages` of PE forward kernel from 5 to 3 fixes LDS
  exhaustion compilation error introduced by async copy.
* Async copy provides a consistent speedup to this case (1.6 median
  speed).

* Update outdated comments in `test_mha.py`

* Fix import bug in `bench_mla_decode.py`

This commit fixes
`ModuleNotFoundError: No module named 'op_tests'`
when running
`python op_tests/op_benchmarks/triton/bench_mla_decode.py`
from AITER project root directory.

* Add tensor parallelism (TP) argument to `bench_mla_decode.py`

* Refactor `bench_mla_decode.py` main function to enable calls from other script

* Integrage MLA decode kernel into attention benchmark script

* Refactor attention benchmark script to enable calls from other scripts

* Rename `bench_mha_models.py` to `bench_attn_models.py`

The script also benchmarks the MLA decode kernel, it isn't just the
regular MHA kernels anymore.

* Enable MLA decode forward kernel with `fp32` type on `gfx950`

* Reducing `num_stages` from 3 to 1 fixes LDS exhaustion compilation
  error introduced by async copy.

* Express sequence lengths in Ks (1K = 1024 tokens)

* Wipe Triton cache to avoid running out of storage space

* Tighten Triton test selection to avoid overshooting

* Filter diff inputs to files reachable in the dependency graph.
* Only use the "benchmark" graph traversal when the diff is
  benchmark-only (avoid pulling in extra tests).

* Remove `kpack` attribute from `gfx950-MLA_DECODE_ROPE-DEFAULT.json`

We can remove `kpack` since it's always 1 on `gfx950`. There's a logic
in Triton compiler to overwrite it to 1 even when `kpack=2`.

* Load attention shapes from JSON file

* Move `bench_attn_models.py` script to `model_benchmarking_tool` directory